### ISSUE TITLE
Error in Wiki

### ISSUE THREAD

**Issue by qutschwalze** [keeps/redmine_wikicipher#12]
Hi, 
after i installed the Plugin, i cant login into the wikipages in Redmine.
Redmine 2.2, Db: Mysql

In the redmine/log/production Log there was this error:

ActionView::Template::Error (undefined method `force_encoding' for #<String:0x7f13e0820988>):
    9: <%= link_to_if_authorized(l(:button_rollback), {:action => 'edit', :id => @page.title, :version => @content.version }, :class => 'icon icon-cancel') unless @content.page.content.version == @content.version %>
    10: <% end %>
    11: <%= link_to_if_authorized(l(:label_history), {:action => 'history', :id => @page.title}, :class => 'icon icon-history') %>
    12: <%= call_hook(:view_wiki_contextual,{:id => @project.identifier, :toggle => params[:decode], :content=>@content, :page =>@page,:version => @content.version }) %>
    13: </div>
    14:
    15: <%= wiki_page_breadcrumb(@page) %>

**Comment by hsilva-keep** [comment]
@qutschwalze @vetmedeu First of all, please accept our apologies for the late answer. 

As far as I understand, this problem is most certainly related to the version of ruby used. In 1.8.x that particular method String.force_encoding does not exist. So, ruby version 1.9.x or higher should be used. 
I'll improve the Readme file to make this clear and I'll close this issue for now (please re-open it if you find the answer unacceptable).
