### ISSUE TITLE
wiki cipher wiki tool bar button appears right handed of the help menu

### ISSUE THREAD

**Issue by cforce** [keeps/redmine_wikicipher#14]
The wiki text edit help menu buttobn shall be outer right side the last toolbar button, but the encryption button is more right. Thats not good for usability.

**Comment by hsilva-keep** [comment]
@cforce First of all, please accept our apologies for the late answer. 
The simple answer is: out of the box its not possible. It could be achieved using https://github.com/tleish/redmine_jstoolbar_ext but this would need changes to our code in order to make it work. 

ATM we can't allocate internal effort to do this as we don't see it as a really needed feature/improvement.

I'll close the issue for now, but if you want to contribute please do it in the form of pull request (and please re-open this issue or post a new one). The community (us included) would appreciate it.
